# fly.toml app configuration file generated for nova-wandering-snow-7308 on 2024-12-30T10:12:25+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nova-wandering-snow-7308'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
